myexe=/media/i9/gamma/workspace/P04_ad/SegFSR-V3/build/SegFSR
iroot=/media/i9/gamma/Exp_ProtoSAR/bent
oroot="/media/i9/gamma/Exp_ProtoSAR/bent/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/cable_gland_000.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_001.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_002.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_003.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_004.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_005.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_006.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_007.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_008.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_009.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_010.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_011.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_012.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_013.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_014.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_015.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_016.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_017.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_018.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_019.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/cable_gland_020.ply              --opath ${oroot}    
${myexe} --ipath_of_ply ${iroot}/dowel_000.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_001.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_002.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_003.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_004.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_005.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_006.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_007.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_008.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_009.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_010.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_011.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_012.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_013.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_014.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_015.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_016.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_017.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_018.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_019.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_020.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_021.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_022.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_023.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_024.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_025.ply              --opath ${oroot}          
${myexe} --ipath_of_ply ${iroot}/dowel_026.ply              --opath ${oroot}          


iroot=/media/i9/gamma/Exp_ProtoSAR/color
oroot="/media/i9/gamma/Exp_ProtoSAR/color/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/foam_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_019.ply              --opath ${oroot}

iroot=/media/i9/gamma/Exp_ProtoSAR/combined
oroot="/media/i9/gamma/Exp_ProtoSAR/combined/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/bagel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_000.ply              --opath ${oroot}       
${myexe} --ipath_of_ply ${iroot}/carrot_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_004.ply              --opath ${oroot}




iroot=/media/i9/gamma/Exp_ProtoSAR/contamination
oroot="/media/i9/gamma/Exp_ProtoSAR/contamination/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/bagel_000.ply              --opath ${oroot}  
${myexe} --ipath_of_ply ${iroot}/bagel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_027.ply              --opath ${oroot}


iroot=/media/i9/gamma/Exp_ProtoSAR/crack
oroot="/media/i9/gamma/Exp_ProtoSAR/crack/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/bagel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_026.ply              --opath ${oroot}

iroot=/media/i9/gamma/Exp_ProtoSAR/cut
oroot="/media/i9/gamma/Exp_ProtoSAR/cut/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/cable_gland_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_026.ply              --opath ${oroot}

iroot=/media/i9/gamma/Exp_ProtoSAR/good
oroot="/media/i9/gamma/Exp_ProtoSAR/good/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/bagel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_027.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/dowel_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/foam_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_027.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_028.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_029.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_030.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_031.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_024.ply              --opath ${oroot}


iroot=/media/i9/gamma/Exp_ProtoSAR/hole
oroot="/media/i9/gamma/Exp_ProtoSAR/hole/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/bagel_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/bagel_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/carrot_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cookie_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_026.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_027.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/peach_028.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/potato_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_021.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_022.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_023.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_024.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_025.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/tire_026.ply              --opath ${oroot}


iroot=/media/i9/gamma/Exp_ProtoSAR/open
oroot="/media/i9/gamma/Exp_ProtoSAR/open/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/rope_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/rope_016.ply              --opath ${oroot}


iroot=/media/i9/gamma/Exp_ProtoSAR/thread
oroot="/media/i9/gamma/Exp_ProtoSAR/thread/out"
rm -rf ${oroot}/*
${myexe} --ipath_of_ply ${iroot}/cable_gland_000.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_001.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_002.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_003.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_004.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_005.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_006.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_007.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_008.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_009.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_010.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_011.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_012.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_013.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_014.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_015.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_016.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_017.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_018.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_019.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_020.ply              --opath ${oroot}
${myexe} --ipath_of_ply ${iroot}/cable_gland_021.ply              --opath ${oroot}